# -*- coding: utf-8 -*-
"""online payment fraud detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-HSLJqFRX9mWpCRbs7FhI6Ga_eMcj6qo
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!chmod 600 /root/.kaggle/kaggle.json

!kaggle datasets download -d rupakroy/online-payments-fraud-detection-dataset

!unzip online-payments-fraud-detection-dataset.zip

import pandas as pd
import numpy as np

data=pd.read_csv("/content/PS_20174392719_1491204439457_log.csv")

data.head(10)

data.tail()

data.info()

data.isnull().sum()

fraud=data[data['isFraud']==0]
not_fraud=data[data['isFraud']==1]

print(data.type.value_counts())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

data["type"] = data["type"].map({"CASH_OUT": 1, "PAYMENT": 2, 
                                 "CASH_IN": 3, "TRANSFER": 4,
                                 "DEBIT": 5})
data["isFraud"] = data["isFraud"].map({0: "No Fraud", 1: "Fraud"})

data.head()

x=np.array(data[['type','amount','oldbalanceOrg',	'newbalanceOrig']])
y=np.array(data[['isFraud']])

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.10,random_state=42)

model=LogisticRegression()

model.fit(xtrain,ytrain)

print(model.score(xtest,ytest))

pred=model.predict(xtest)

# prediction
#features = [type, amount, oldbalanceOrg, newbalanceOrig]
features = np.array([[4, 4700.60, 9000.60, 0.0]])
print(model.predict(features))

from sklearn.metrics import classification_report
print(classification_report(ytest,pred))